### ISSUE TITLE
Fabric mod doesn't support versions above 15.7 of the Fabric Loader

### ISSUE THREAD

**Issue by HueyCan** [hexnowloading/DungeonNowLoading#2]
Trying to load this mod with any version above 15.7 of the Fabric Loader (15.10 for example) will give you an incompatibility error.
Tested this isolated from other mods and DNL itself is causing this issue.

**Comment by hexnowloading** [comment]
I'll release fix for that soon!

**Comment by HueyCan** [comment]
As of version 1.0.1, DNL has fixed this issue
Closing this
