### ISSUE TITLE
Incompatibility with True Ending | Ender Dragon dies instantly

### ISSUE THREAD

**Issue by mxKeaton** [hexnowloading/DungeonNowLoading#6]
After installing DNL, the changed Ender Dragon from True Ending dies the moment it gets summoned, naturally and via command.

**Comment by hexnowloading** [comment]
There's nothing I changed about Ender Dragon so I'm not sure its from DNL.

**Comment by Spudstak** [comment]
Unfortunately I am also experiencing this issue. I tried going into the end without DNL and with True Ending and the dragon didn't instantly die but with both true ending and DNL installed the dragon did instantly die, regardless of other end mods installed.

**Comment by hexnowloading** [comment]
I see, I'll try to fix it. Thank you for the report

**Comment by hexnowloading** [comment]
It seems like the developer of the true end doesn't have the source code public...
