### ISSUE TITLE
No creative tab or JEI results, also no dungeon created [Fabric] [1.19.2]

### ISSUE THREAD

**Issue by Wizardon777** [hexnowloading/DungeonNowLoading#7]
Mod version: 1.8.2
Fabric Version: 0.15.10

As far as I can tell, there is no error or incompatibility message in any log.
And the mod is loading fine (see image below)
![Untitled](https://github.com/hexnowloading/DungeonNowLoading/assets/22551232/cdbb036f-7a14-46f8-9c3a-85a9c6e430b7)

**Comment by hexnowloading** [comment]
1.19.2 version is a datapack, so doesn't have anything from the mod
